# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nticms/Development/TB_SDR/adi/hdl/projects/fmcomms2/tef1002/fmcomms2_tef1002.srcs/sources_1/bd/system/ip/system_util_ad9361_adc_fifo_0/system_util_ad9361_adc_fifo_0.xci
# IP: The module: 'system_util_ad9361_adc_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nticms/Development/TB_SDR/adi/hdl/projects/fmcomms2/tef1002/fmcomms2_tef1002.gen/sources_1/bd/system/ip/system_util_ad9361_adc_fifo_0/util_wfifo_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ad9361_adc_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nticms/Development/TB_SDR/adi/hdl/projects/fmcomms2/tef1002/fmcomms2_tef1002.srcs/sources_1/bd/system/ip/system_util_ad9361_adc_fifo_0/system_util_ad9361_adc_fifo_0.xci
# IP: The module: 'system_util_ad9361_adc_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nticms/Development/TB_SDR/adi/hdl/projects/fmcomms2/tef1002/fmcomms2_tef1002.gen/sources_1/bd/system/ip/system_util_ad9361_adc_fifo_0/util_wfifo_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ad9361_adc_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
